# Generated by Django 4.2 on 2025-03-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='sonido',
            field=models.FileField(null=True, upload_to='media/sonido'),
        ),
    ]
