# Generated by Django 4.2.11 on 2025-03-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0002_alerta_sonido'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='centro_emision',
            field=models.CharField(default='0055', max_length=4),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='sonido',
            field=models.FileField(null=True, upload_to='sonido'),
        ),
    ]
