# Generated by Django 4.2.11 on 2025-03-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0003_alerta_centro_emision_alter_alerta_sonido'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='comanda',
            field=models.BooleanField(default=False),
        ),
    ]
