# Generated by Django 4.2.11 on 2025-03-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0004_alerta_comanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='control_producto',
            field=models.BooleanField(default=False),
        ),
    ]
