# Generated by Django 4.2 on 2025-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('puerto', models.IntegerField(default=80)),
                ('usuario', models.CharField(default='a', max_length=20)),
                ('contraseña', models.CharField(default='aa', max_length=20)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
