# Generated by Django 4.2 on 2025-03-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='puerto',
            field=models.IntegerField(default=8080),
        ),
    ]
