# Generated by Django 4.2.11 on 2025-03-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_server_puerto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='estado',
        ),
    ]
